version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # - n 20.10.0
      - npm install
      - echo Installing dependencies...
  build:
    commands:
      #list all files
      - ls -la
      - echo "=== git rev ==="
      - git rev-parse HEAD || true
      - echo "=== stop_server.sh ==="
      - sed -n '1,20p' scripts/stop_server.sh
      - echo "=== start_server.sh ==="
      - sed -n '1,20p' scripts/start_server.sh
      - echo "=== appspec.yml ==="
      - sed -n '1,50p' appspec.yml
      - echo Build phase...
      - echo enviroment variable
      - echo $ENV_VAR

artifacts:
  files:
    - "**/*"
  base-directory: ./
